version: "3"

services:
  memcached:
    container_name: memcached
    image: tutum/memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_PASS=admin
    networks:
      - server-network

  node:
    container_name: node
    build: ./
    env_file: .env
    ports:
      - "4000:4000"
      - "4001:4001"
      - "56745:56745"
    volumes:
      - ./:/app
    links:
      - memcached
    networks:
      - server-network
    command: yarn start

networks: 
  server-network:
    driver: bridge