export const ENV_NAMES = {
  DATABASE_URL: 'DATABASE_URL',
  JWT: 'JWT',
  PAY_PAL: 'PAY_PAL',
  CRYPTO_SECRET_KEY: 'CRYPTO_SECRET_KEY',
  USE_CACHE: 'USE_CACHE',
  CACHE_EXPIRATION: 'CACHE_EXPIRATION',
  MEMCACHEDCLOUD: 'MEMCACHEDCLOUD',
  DEV: 'DEV_MODE'
}

export const SERVICES_NAMES = {
  CACHE_CLIENT: 'CACHE_CLIENT',
  WS_CLIENTS: 'WS_CLIENTS',
}