name: Deployment to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker stop memcached node
            docker rm memcached node
            rm -rf server
            rm -rf ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone git@github.com:viniciusnw/fwy-server.git server
            cd server/
            yarn
            docker-compose up --build
            exit $?
            EOF
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
