name: Deployment to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: './server'
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker stop memcached node
            docker rm memcached node
            cd server/
            git pull origin master
            exit $?
            EOF
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
