name: Deployment to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            docker stop memcached node
            docker rm memcached node
            rm -rf server
            ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
            git clone git@bitbucket.org:viniciusnw/server.git
            cd server/
            docker-compose up --build
            git pull origin master
            exit $?
            EOF
            echo "Deploy Finished \O"
